spring.application.name=product-api

## Application port
server.port=8081
## defalt connection pool 
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=postgres
spring.datasource.password=12345678

## Default schema
spring.flyway.schemas=products
spring.jpa.properties.hibernate.default_schema=products
spring.flyway.locations=classpath:db/migration